apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app: inventory
    tier: backend
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 8080
  selector:
    app: inventory
    tier: backend
